### ISSUE TITLE
compatible with wasm-unknown-unknown target?

### ISSUE THREAD

**Issue by FrankReh** [jonhoo/async-bincode#10]
Was curious whether this relied on anything requiring an OS or if it could run on bare metal, specifically a wasm-unknown-unknown target. On the surface, it sounded like it just relied on futures, which do work in wasm, given an executor compatible with wasm.

But the file src/futures.rs uses std::task so I'm guessing not?

**Comment by jonhoo** [comment]
`std::task` _should_ work fine on WASM I believe, and I don't think there's anything else in the crate that _requires_ that you run on an OS directly. You will need an executor though, and one that is compatible with either the tokio or futures async I/O traits, but apart from that you _should_ be good to go.

**Comment by vpzomtrrfrt** [comment]
I've been using this crate in wasm32-unknown-unknown, seems to work fine
